// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsnbssJDS1hhvYguUzLv6ULgrFC1Xe15k',
    appId: '1:567835238062:web:1573b5776404a5d25c173f',
    messagingSenderId: '567835238062',
    projectId: 'e-shop-app-43ef1',
    authDomain: 'e-shop-app-43ef1.firebaseapp.com',
    storageBucket: 'e-shop-app-43ef1.firebasestorage.app',
    measurementId: 'G-BHQF69GDR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_OgBtpy6D0WA4hF6DA9iZfIB-w1NRBsM',
    appId: '1:567835238062:android:3f671d2932f5faa15c173f',
    messagingSenderId: '567835238062',
    projectId: 'e-shop-app-43ef1',
    storageBucket: 'e-shop-app-43ef1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR19w74NlOEqZHOJZVkKggm_SJuOEQU_w',
    appId: '1:567835238062:ios:c6b6678bea8decb75c173f',
    messagingSenderId: '567835238062',
    projectId: 'e-shop-app-43ef1',
    storageBucket: 'e-shop-app-43ef1.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsnbssJDS1hhvYguUzLv6ULgrFC1Xe15k',
    appId: '1:567835238062:web:b695b7ca250bb3b65c173f',
    messagingSenderId: '567835238062',
    projectId: 'e-shop-app-43ef1',
    authDomain: 'e-shop-app-43ef1.firebaseapp.com',
    storageBucket: 'e-shop-app-43ef1.firebasestorage.app',
    measurementId: 'G-6TZVZTYR8Y',
  );

}